### ISSUE TITLE
[Bug] ENV COMPOSER_MEMORY_LIMIT should NOT be explicitly defined

### ISSUE THREAD

**Issue by jelen07** [nanodoc/php#13]
The current limit may not be enough. For example when installing dependency via composer.
The limit can be found [here](https://github.com/nanodoc/php/blob/5d47532b5644f7a6f9d2783e20a13e558e23bb5e/base/Dockerfile#L49).

**Comment by misaon** [comment]
Maybe remove COMPOSER_MEMORY_LIMIT environment and keep this max memory value in php.ini only. I will make some tests.
